In [1]:
import numpy as np

In [2]:
# slicing deos not create new array

In [3]:
# fancy indexing create new array

In [4]:
# swapaxes deos not create new array

In [5]:
# adding series as a column in data frame will only create a view ,
#changes made in series will be reflected back in data frame

In [6]:
import pandas as pd

In [7]:
aa = np.arange(10)

In [8]:
from numpy.random import randn


In [9]:
aa.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [10]:
data1 = [6, 7.5, 8, 0, 1]

In [11]:
arr = np.array(data1)

In [12]:
arr


array([6. , 7.5, 8. , 0. , 1. ])

In [13]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [14]:
arr2 = np.array(data2)

In [15]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
arr2.shape

(2, 4)

In [17]:
arr.dtype

dtype('float64')

In [18]:
arr2.dtype

dtype('int64')

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [21]:
np.empty((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
arr = np.array([1,2,3,4,5])

In [24]:
arr.dtype


dtype('int64')

In [25]:
float_arr = arr.astype(np.float64)

In [26]:
float_arr.dtype

dtype('float64')

In [27]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [28]:
arr


array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [29]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [30]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype = np.string_)

In [31]:
numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [32]:
int_array = np.arange(10)

In [33]:
calibers = np.array([.22, .270, .357, .380, .44], dtype = np.float)

In [34]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [35]:
empty_uint32 = np.empty(8, dtype = 'u4')

In [36]:
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [37]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [38]:
arr3d


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [39]:
arrcopy = arr3d[0].copy()

In [40]:
arrcopy

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
arr3d[0] = 64

In [42]:
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [43]:
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [44]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [45]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [48]:
data = randn(7, 4)

In [49]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [50]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [51]:
data

array([[ 1.2707354 ,  0.13253373,  0.18344181,  1.5425932 ],
       [ 1.57569625, -0.78544985, -1.80609615,  0.38055923],
       [-1.98096164, -1.48061303,  0.83315907, -1.44980231],
       [-1.01426041,  1.52213833,  1.66289409, -0.31543477],
       [ 0.49101645, -1.0900754 , -0.14293579,  0.24496691],
       [-0.4456629 , -2.44940849,  0.4551154 ,  0.31884301],
       [ 0.35589084,  0.37798574,  0.91191563,  0.51877897]])

In [52]:
names== 'Bob'

array([ True, False, False,  True, False, False, False])

In [53]:
data[names == 'Bob']

array([[ 1.2707354 ,  0.13253373,  0.18344181,  1.5425932 ],
       [-1.01426041,  1.52213833,  1.66289409, -0.31543477]])

In [54]:
data[names == 'Bob', 2:]

array([[ 0.18344181,  1.5425932 ],
       [ 1.66289409, -0.31543477]])

In [55]:
data<0

array([[False, False, False, False],
       [False,  True,  True, False],
       [ True,  True, False,  True],
       [ True, False, False,  True],
       [False,  True,  True, False],
       [ True,  True, False, False],
       [False, False, False, False]])

In [56]:
arr = np.empty((8, 4))

In [57]:
for i in range(8):
    arr[i]=i

In [58]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [59]:
aa =arr[[6,4,0,2]]

In [60]:
arr = np.arange(32).reshape((8, 4))

In [61]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [62]:
arr[[1, 5, 7, 2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [63]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]] # case study

array([ 4, 23, 29, 10])

In [64]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]  # right way to produce row column manipulation

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [65]:
obj = pd.Series([4, 7, -5, 3])

In [66]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [67]:
obj[0]

4

In [68]:
obj[1]

7

In [69]:
obj = pd.Series([4,7,-5,3])

In [70]:
obj.values

array([ 4,  7, -5,  3])

In [71]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [72]:
obj2 = pd.Series([4,7,-5, 3], index =['d', 'b', 'a', 'c'])

In [73]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [74]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [75]:
obj2[obj2>0]

d    4
b    7
c    3
dtype: int64

In [76]:
obj2* 2

d     8
b    14
a   -10
c     6
dtype: int64

In [77]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [78]:
'b' in obj2

True

In [79]:
'e' in obj2

False

In [80]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [81]:
obj3 = pd.Series(sdata)

In [82]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [83]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [84]:
obj4 = pd.Series(sdata, index = states)

In [85]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [86]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [87]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [88]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [89]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
'year': [2000, 2001, 2002, 2001, 2002],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}

In [90]:
frame = pd.DataFrame(data)

In [91]:
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [92]:
frame = pd.DataFrame(data, columns = ['state', 'year', 'pop'])

In [93]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [94]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [99]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [101]:
frame2 = pd.DataFrame(data, columns = ['year', 'state', 'pop', 'debt'],
                      index = ['one', 'two', 'three', 'four', 'five'])

In [102]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [103]:
frame2.index

Index(['one', 'two', 'three', 'four', 'five'], dtype='object')

In [104]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [105]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [108]:
frame2['state']['one'] # this will not work -> frame2['state', 'one']

'Ohio'

In [109]:
frame2.ix['three']

/home/lalitk/machine_learning/menv/lib/python3.5/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [116]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [117]:
frame2['debt'] = 16.5

In [118]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [119]:
frame2['debt'] = np.arange(5.)

In [122]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [125]:
a = [1,2,3,4,5]

In [126]:
frame['total'] = a

In [127]:
frame

state  year  pop  total
0    Ohio  2000  1.5      1
1    Ohio  2001  1.7      2
2    Ohio  2002  3.6      3
3  Nevada  2001  2.4      4
4  Nevada  2002  2.9      5

In [128]:
a [2] = 150

In [129]:
frame

state  year  pop  total
0    Ohio  2000  1.5      1
1    Ohio  2001  1.7      2
2    Ohio  2002  3.6      3
3  Nevada  2001  2.4      4
4  Nevada  2002  2.9      5

In [130]:
#re indexing  create a new object with data conformed to new object.

In [131]:
obj = pd.Series([4.5,7.2, -5.3, 3.6], index = ['d', 'b', 'a', 'c'])

In [132]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [133]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [134]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [135]:
obj.reindex(['a', 'b', 'c', 'd', 'e'], fill_value = 0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [136]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index = [0,2,4])

In [137]:
obj3.reindex(range(6), method = 'ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [138]:
#in case of data frame reindexing first for rows then columns

In [139]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)), index = ['a', 'c', 'd'],
                    columns = ['Ohio', 'Texas', 'California'])

In [140]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [141]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [142]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [144]:
states = ['Texas','Utah', 'California']

In [145]:
frame.reindex(columns = states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [146]:
#dropping entries from  an axis

In [147]:
obj = pd.Series(np.arange(5.), index = ['a', 'b', 'c', 'd', 'e'])

In [148]:
new_obj = obj.drop('c')

In [149]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [150]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [152]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),

index=['Ohio', 'Colorado', 'Utah', 'New York'],

columns=['one', 'two', 'three', 'four'])

In [153]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [154]:
data.drop(['Colorado','Utah'])

one  two  three  four
Ohio        0    1      2     3
New York   12   13     14    15

In [155]:
data.drop('two', axis = 1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [156]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [157]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [159]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [160]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [161]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [162]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [163]:
obj['b':'c'] = 5

In [164]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [166]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),index =['Ohio', 'Colorado', 'Utah', 'New York'],
                 columns = ['one', 'two', 'three', 'four'])

In [167]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [168]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [169]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [170]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [171]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [12]:
#  handling missing data

In [13]:
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])

In [14]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [15]:
string_data[0] = None

In [16]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [17]:
from numpy import nan as NA

In [18]:
data = pd.Series([1, NA, 3.5, NA, 7])

In [19]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [20]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [22]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA],
[NA, NA, NA], [NA, 6.5, 3.]])

In [23]:
cleaned = data.dropna()

In [24]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0